### ISSUE TITLE
how to multithread JOD + Libraoffice

### ISSUE THREAD

**Issue by kbhagvati** [jodconverter/jodconverter-samples#9] opened 2023-05-12 11:16 UTC
Can we multithread JOD converter for each and every request as i'm using LocalOfficeManager to converter the file.
while running multiple request simultaneously, i'm facing the issue (one request is processed and other task is cancelled) , while running as single request it seems to be working fine.
if you could provide the sample code of multithreading that would be helpful.
i'm using following logic to convert the file to PDF:

```java
LocalOfficeManager officeManager = LocalOfficeManager.builder()
    .portNumbers(2002, 2003, 2004, 2005)
    .officeHome("//opt//libreoffice7.5")
    //.maxTasksPerProcess(200)
    //.taskQueueTimeout(120000L)
    .existingProcessAction(ExistingProcessAction.CONNECT)
    .install()
    .build(); 
try {
    // Start an office process and connect to the started instance (on port 2002).
    officeManager.start();
    // Convert
    final DocumentConverter converter = LocalConverter.builder().officeManager(officeManager).build();
    final DocumentFormat sourceFormat = DefaultDocumentFormatRegistry.getFormatByExtension(FilenameUtils.getExtension(sourceFileName));
    //final DocumentFormat targetFormat = DefaultDocumentFormatRegistry.getFormatByExtension(FilenameUtils.getExtension(targetFileName));
    final DocumentFormat targetFormat = DefaultDocumentFormatRegistry.getFormatByExtension("pdf");
    converter.convert(inputFile).as(sourceFormat).to(outputFile).as(targetFormat).execute();
} finally {
    // Stop the office process
    OfficeUtils.stopQuietly(officeManager);
}
```

**Comment by sbraconnier** [comment] 2023-05-12 14:18
JODConverter is working just fine using multithreading. There is a [Stress Test here](https://github.com/jodconverter/jodconverter/blob/master/jodconverter-local/src/integTest/java/org/jodconverter/local/StressITest.java) that is working fine.

The problem is probably the way you are using it. Are you creating an office manager for each conversion ?? In order to support multi-threading, you must create a manager when the application starts and close it when the application stops. Each conversion will use the same manager (and could use the same converter too is its configuration is the same for each conversion).

The 3 projects [here](https://github.com/jodconverter/jodconverter-samples/tree/main/samples) are all application that supports multiple requests simultaneously.

**Closed as completed** 2023-09-13 05:10 UTC
